version = 0.1
[default.deploy.parameters]
stack_name = "lambdas"
resolve_s3 = true
s3_prefix = "lambdas"
region = "us-east-1"
profile = "gutkedu-terraform"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
image_repositories = []
